#!/usr/bin/env escript
%% -*- erlang -*-
%%! -pa ebin -sname empty_plt
%% vim: set ft=erlang ts=4 sw=4 et:

main([Out]) ->
    case purity_plt:save(purity_plt:new(), Out) of
        ok -> ok;
        {error, Rsn} ->
            io:format("ERROR: ~s", [Rsn]),
            halt(1)
    end.

