#!/bin/zsh

scripts=$(dirname $0)
source $scripts/common
tests=test

main() {
    dir=$(make_tempfile -dt ptests.XXXXXXX)
    P=0
    F=0
    for test in $@; do
        for exp in $($scripts/extract ${test:r}.erl $dir); do
            runtest $test $exp $dir && passed $exp || failed
        done
    done
    rmdir --ignore-fail-on-non-empty $dir
    report

    extra_tests
}

runtest() { erl_exec runtest main $@ }
passed() { ((P++)); rm $1 }
failed() { ((F++)) }
report() {
    if ((F>0)); then echo "$F/$((P+F)) TESTS FAILED" ; exit 1
    else echo "ALL $P TESTS PASSED"; fi
}

extra_tests() {
    $tests/duplicates $tests/d1/a.erl $tests/d2/a.erl
    $tests/combined_analysis $tests/*.erl
}

main $@
