#!/bin/zsh

scripts=$(dirname $0)
source $scripts/common

main() {
    dir=$(make_tempfile -dt ptests.XXXXXXX)
    P=0
    F=0
    for test in $@; do
        for exp in $($scripts/extract ${test:r}.erl $dir); do
            runtest $test $exp $dir && passed $exp || failed
        done
    done
    rmdir $dir
    report
}

runtest() { erl_exec runtest main $@ }
passed() { ((P++)); rm $1 }
failed() { ((F++)) }
report() {
    if ((F>0)); then echo "$F/$((P+F)) TESTS FAILED"
    else echo "ALL $P TESTS PASSED"; fi
}

main $@
